version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: summoners-grid-postgres
    environment:
      POSTGRES_DB: summoners_grid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: summoners-grid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Redis GUI for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: summoners-grid-redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - dev-tools

  # Optional: PostgreSQL admin for development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: summoners-grid-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@summoners-grid.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - dev-tools

volumes:
  postgres_data:
  redis_data: