/**
 * Alpha Set - Unique/Special Cards
 *
 * Special cards generated by Named Summons and other unique effects.
 * Card definitions follow the schema defined in @summoners-grid/engine.
 */

export const uniqueCards = [
  // 050 - Follow Me! (Alrecht Barkstep's unique card)
  {
    definitionId: '050-follow-me',
    name: 'Follow Me!',
    type: 'action',
    rarity: 'common',
    attribute: 'neutral',
    set: 'alpha',
    cardNumber: 50,
    speed: 'action',
    destination: 'removed',
    requirements: [
      {
        type: 'controlsNamedSummon',
        params: { name: 'Alrecht Barkstep, Scoutmaster' },
      },
    ],
    selectionPrompts: [
      {
        id: 'caster',
        type: 'unit',
        filter: 'controlled && name == "Alrecht Barkstep, Scoutmaster"',
      },
      {
        id: 'target',
        type: 'unit',
        filter: 'controlled',
      },
      {
        id: 'destination',
        type: 'position',
        filter: 'unoccupied && adjacentTo(caster)',
      },
    ],
    effects: [
      {
        type: 'teleportToAdjacent',
        params: {
          target: 'target',
          adjacentTo: 'caster',
          ignoreImmobilize: true,
          isNotMovement: true,
        },
      },
    ],
    flavorText: 'Teleport target summon you control to an unoccupied space adjacent to Alrecht Barkstep. This is not movement and ignores immobilize.',
  },
];
