name: PR Preview

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for preview
      run: npm run build
      env:
        NODE_ENV: development
        
    - name: Upload preview artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-preview-${{ github.event.number }}
        path: ./dist
        retention-days: 30